import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from './StoreProvider';
import Footer from '@/components/Footer';
import Navbar from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div>
        <Navbar />
        <StoreProvider>
          <main className="">{children}</main>
        </StoreProvider>
        <Footer />
      </div>
    </html>
  );
}
